// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {updater} from '../models';
import {main} from '../models';
import {androidclient} from '../models';

export function CheckForUpdates():Promise<updater.Info>;

export function GetAuthenticatedProxyAccess():Promise<main.AuthenticatedProxyAccess>;

export function GetSnapshot():Promise<main.DesktopSnapshot>;

export function InstallUpdate():Promise<void>;

export function OpenProjectPage():Promise<void>;

export function ReconnectMobile():Promise<androidclient.OperationResponse>;

export function RefreshAdapters():Promise<void>;

export function RefreshPublicIP():Promise<androidclient.OperationResponse>;

export function ResetTraffic():Promise<void>;

export function SelectAdapter(arg1:string):Promise<void>;

export function SetExclusiveMode(arg1:boolean):Promise<void>;

export function SetIPMode(arg1:string):Promise<void>;

export function StartTethering():Promise<androidclient.OperationResponse>;

export function StopTethering():Promise<androidclient.OperationResponse>;
