// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAuthenticatedProxyAccess() {
  return window['go']['main']['App']['GetAuthenticatedProxyAccess']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function ReconnectMobile() {
  return window['go']['main']['App']['ReconnectMobile']();
}

export function RefreshAdapters() {
  return window['go']['main']['App']['RefreshAdapters']();
}

export function RefreshPublicIP() {
  return window['go']['main']['App']['RefreshPublicIP']();
}

export function ResetTraffic() {
  return window['go']['main']['App']['ResetTraffic']();
}

export function SelectAdapter(arg1) {
  return window['go']['main']['App']['SelectAdapter'](arg1);
}

export function SetExclusiveMode(arg1) {
  return window['go']['main']['App']['SetExclusiveMode'](arg1);
}

export function SetIPMode(arg1) {
  return window['go']['main']['App']['SetIPMode'](arg1);
}

export function StartTethering() {
  return window['go']['main']['App']['StartTethering']();
}

export function StopTethering() {
  return window['go']['main']['App']['StopTethering']();
}
